#! /bin/sh

jtpDamlHome=../../../jtp/damlEd
libDir=${jtpDamlHome}/lib

for i in ${libDir}/*.jar ; do
    if [ "$CP" != "" ]; then
	CP=${CP}:$i
    else
	CP=$i
    fi
done

CP=${CP}

java -classpath ../../..:$CP $1 $2
